{
 "title": "Pirate - Mining Pool  Monitor New",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Miners",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Home-231",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "poolStats",
     "select": [
      [
       { "params": [ "algos_equihash_workers" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://192.168.2.231:8085/api/stats"
      }
     ]
    },
    {
     "alias": "local-3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "poolStats",
     "select": [
      [
       { "params": [ "algos_equihash_workers" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://192.168.2.184:8085/api/stats"
      }
     ]
    }
   ]
  },
  {
   "title": "Confirmed Blocks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "alias": "Home",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "limit": "0",
     "measurement": "poolStats",
     "query": "SELECT mean(\"pools_komodo_blocks_pending\") FROM \"poolStats\" WHERE $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       {
        "params": [
         "pools_pirate-chain_blocks_confirmed"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "slimit": "20",
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://192.168.2.231:8085/api/stats"
      }
     ]
    },
    {
     "alias": "local-138",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "limit": "0",
     "measurement": "poolStats",
     "query": "SELECT non_negative_difference(difference(distinct(\"pools_pirate-chain_blocks_confirmed\"))) FROM \"poolStats\" WHERE (\"url\" = 'http://192.168.2.226:8085/api/stats') AND $timeFilter GROUP BY time(30m) fill(none) LIMIT 100 SLIMIT 100",
     "select": [
      [
       {
        "params": [
         "pools_pirate-chain_blocks_confirmed"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "difference"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "slimit": "20",
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://192.168.2.138:8087/api/stats"
      }
     ]
    },
    {
     "alias": "local-3",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "limit": "0",
     "measurement": "poolStats",
     "query": "SELECT non_negative_difference(difference(distinct(\"pools_pirate-chain_blocks_confirmed\"))) FROM \"poolStats\" WHERE (\"url\" = 'http://192.168.2.226:8085/api/stats') AND $timeFilter GROUP BY time(30m) fill(none) LIMIT 100 SLIMIT 100",
     "select": [
      [
       {
        "params": [
         "pools_pirate-chain_blocks_confirmed"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "difference"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "slimit": "20",
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://192.168.2.184:8085/api/stats"
      }
     ]
    }
   ]
  },
  {
   "title": "Blocks Pending mini graph",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Home",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "poolStats",
     "query": "SELECT mean(\"pools_komodo_blocks_pending\") FROM \"poolStats\" WHERE $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       {
        "params": [
         "pools_pirate-chain_blocks_pending"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://192.168.2.231:8085/api/stats"
      }
     ]
    },
    {
     "alias": "Building",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "poolStats",
     "query": "SELECT mean(\"pools_komodo_blocks_pending\") FROM \"poolStats\" WHERE $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       {
        "params": [
         "pools_pirate-chain_blocks_pending"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://pool1.entrustus.org:8085/api/stats"
      }
     ]
    },
    {
     "alias": "138-testing",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "poolStats",
     "query": "SELECT mean(\"pools_komodo_blocks_pending\") FROM \"poolStats\" WHERE $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       {
        "params": [
         "pools_pirate-chain_blocks_pending"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://pool1.entrustus.org:8087/api/stats"
      }
     ]
    },
    {
     "alias": "local-138",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "poolStats",
     "query": "SELECT mean(\"pools_komodo_blocks_pending\") FROM \"poolStats\" WHERE $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       {
        "params": [
         "pools_pirate-chain_blocks_pending"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://192.168.2.138:8087/api/stats"
      }
     ]
    },
    {
     "alias": "local-3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "poolStats",
     "query": "SELECT mean(\"pools_komodo_blocks_pending\") FROM \"poolStats\" WHERE $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       {
        "params": [
         "pools_pirate-chain_blocks_pending"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://192.168.2.184:8085/api/stats"
      }
     ]
    }
   ]
  },
  {
   "title": "Blocks Paid ${__from:date:MM-DD-YY} To ${__to:date:MM-DD-YY}",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Home-231",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "limit": "0",
     "measurement": "poolStats",
     "select": [
      [
       {
        "params": [
         "pools_pirate-chain_blocks_confirmed"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "spread"
       },
       { "params": [ "+0" ], "type": "math" }
      ]
     ],
     "slimit": "100",
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://192.168.2.231:8085/api/stats"
      }
     ]
    },
    {
     "alias": "local-3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "limit": "0",
     "measurement": "poolStats",
     "select": [
      [
       {
        "params": [
         "pools_pirate-chain_blocks_confirmed"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "spread"
       },
       { "params": [ "+0" ], "type": "math" }
      ]
     ],
     "slimit": "100",
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://192.168.2.184:8085/api/stats"
      }
     ]
    },
    { "expression": "($B+$M)*4*0.34", "type": "math" }
   ]
  },
  {
   "title": "Immature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Building",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "poolStats",
     "select": [
      [
       {
        "params": [
         "pools_pirate-chain_blocks_pending"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://pool1.entrustus.org:8085/api/stats"
      }
     ]
    },
    {
     "alias": "building-138",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "poolStats",
     "select": [
      [
       {
        "params": [
         "pools_pirate-chain_blocks_pending"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://pool1.entrustus.org:8087/api/stats"
      }
     ]
    },
    {
     "alias": "Home",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "poolStats",
     "select": [
      [
       {
        "params": [
         "pools_pirate-chain_blocks_pending"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://192.168.2.231:8085/api/stats"
      }
     ]
    },
    {
     "alias": "local-138",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "poolStats",
     "select": [
      [
       {
        "params": [
         "pools_pirate-chain_blocks_pending"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://192.168.2.138:8087/api/stats"
      }
     ]
    },
    {
     "alias": "local-3",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "poolStats",
     "select": [
      [
       {
        "params": [
         "pools_pirate-chain_blocks_pending"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://192.168.2.184:8085/api/stats"
      }
     ]
    }
   ]
  },
  {
   "title": "Duplicated",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "Building",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "poolStats",
     "select": [
      [
       {
        "params": [
         "pools_pirate-chain_blocks_blocksDuplicate"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "spread"
       },
       { "params": [ "+0" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://pool1.entrustus.org:8085/api/stats"
      }
     ]
    },
    {
     "alias": "building-138",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "poolStats",
     "select": [
      [
       {
        "params": [
         "pools_pirate-chain_blocks_blocksDuplicate"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "spread"
       },
       { "params": [ "+0" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://pool1.entrustus.org:8087/api/stats"
      }
     ]
    },
    {
     "alias": "Home",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "poolStats",
     "select": [
      [
       {
        "params": [
         "pools_pirate-chain_blocks_blocksDuplicate"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "spread"
       },
       { "params": [ "+0" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://192.168.2.231:8085/api/stats"
      }
     ]
    },
    {
     "alias": "local-138",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "poolStats",
     "select": [
      [
       {
        "params": [
         "pools_pirate-chain_blocks_blocksDuplicate"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "spread"
       },
       { "params": [ "+0" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://192.168.2.138:8087/api/stats"
      }
     ]
    },
    {
     "alias": "local-3",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "poolStats",
     "select": [
      [
       {
        "params": [
         "pools_pirate-chain_blocks_blocksDuplicate"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "spread"
       },
       { "params": [ "+0" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://192.168.2.184:8085/api/stats"
      }
     ]
    }
   ]
  },
  {
   "title": "Rejected",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "Building",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "poolStats",
     "select": [
      [
       {
        "params": [
         "pools_pirate-chain_blocks_blocksRejected"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "spread"
       },
       { "params": [ "+0" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://pool1.entrustus.org:8085/api/stats"
      }
     ]
    },
    {
     "alias": "building-138",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "poolStats",
     "select": [
      [
       {
        "params": [
         "pools_pirate-chain_blocks_blocksRejected"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "spread"
       },
       { "params": [ "+0" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://pool1.entrustus.org:8087/api/stats"
      }
     ]
    },
    {
     "alias": "Home",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "poolStats",
     "select": [
      [
       {
        "params": [
         "pools_pirate-chain_blocks_blocksRejected"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "spread"
       },
       { "params": [ "+0" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://192.168.2.231:8085/api/stats"
      }
     ]
    },
    {
     "alias": "local-138",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "poolStats",
     "select": [
      [
       {
        "params": [
         "pools_pirate-chain_blocks_blocksRejected"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "spread"
       },
       { "params": [ "+0" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://192.168.2.138:8087/api/stats"
      }
     ]
    },
    {
     "alias": "local-3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "poolStats",
     "select": [
      [
       {
        "params": [
         "pools_pirate-chain_blocks_blocksRejected"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "spread"
       },
       { "params": [ "+0" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://192.168.2.184:8085/api/stats"
      }
     ]
    }
   ]
  },
  {
   "title": "Orphaned",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "Building",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "poolStats",
     "select": [
      [
       {
        "params": [
         "pools_pirate-chain_blocks_kicked"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "spread"
       },
       { "params": [ "+0" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://pool1.entrustus.org:8085/api/stats"
      }
     ]
    },
    {
     "alias": "building-138",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "poolStats",
     "select": [
      [
       {
        "params": [
         "pools_pirate-chain_blocks_kicked"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "spread"
       },
       { "params": [ "+0" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://pool1.entrustus.org:8087/api/stats"
      }
     ]
    },
    {
     "alias": "Home",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "poolStats",
     "select": [
      [
       {
        "params": [
         "pools_pirate-chain_blocks_kicked"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "spread"
       },
       { "params": [ "+0" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://192.168.2.231:8085/api/stats"
      }
     ]
    },
    {
     "alias": "local-138",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "poolStats",
     "select": [
      [
       {
        "params": [
         "pools_pirate-chain_blocks_kicked"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "spread"
       },
       { "params": [ "+0" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://192.168.2.138:8087/api/stats"
      }
     ]
    },
    {
     "alias": "local-3",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "poolStats",
     "select": [
      [
       {
        "params": [
         "pools_pirate-chain_blocks_kicked"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "spread"
       },
       { "params": [ "+0" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://192.168.2.184:8085/api/stats"
      }
     ]
    }
   ]
  },
  {
   "title": "Wallet Balance",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Building",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "wallet_balance",
     "query": "SELECT mean(\"gauge\") FROM \"komodo_wallet_balance\" WHERE (\"pirate_wallet\" = 'http://192.168.2.241:9003/metrics' AND \"type\" = 'private') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "pirate_wallet",
       "operator": "=",
       "value": "http://pool1.entrustus.org:9003/metrics"
      }
     ]
    },
    {
     "alias": "Home",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "wallet_balance",
     "query": "SELECT mean(\"gauge\") FROM \"komodo_wallet_balance\" WHERE (\"pirate_wallet\" = 'http://192.168.2.241:9003/metrics' AND \"type\" = 'private') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "pirate_wallet",
       "operator": "=",
       "value": "http://192.168.2.231:9003/metrics"
      }
     ]
    },
    {
     "alias": "local-138",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "wallet_balance",
     "query": "SELECT mean(\"gauge\") FROM \"komodo_wallet_balance\" WHERE (\"pirate_wallet\" = 'http://192.168.2.241:9003/metrics' AND \"type\" = 'private') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "pirate_wallet",
       "operator": "=",
       "value": "http://192.168.2.138:9003/metrics"
      }
     ]
    },
    {
     "alias": "local-3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "wallet_balance",
     "query": "SELECT mean(\"gauge\") FROM \"komodo_wallet_balance\" WHERE (\"pirate_wallet\" = 'http://192.168.2.241:9003/metrics' AND \"type\" = 'private') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "pirate_wallet",
       "operator": "=",
       "value": "http://192.168.2.184:9003/metrics"
      }
     ]
    }
   ]
  },
  {
   "title": "Miner Hashrates",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "MHs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Building",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "poolStats",
     "select": [
      [
       { "params": [ "pools_pirate-chain_hashrate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000/1000/1000/1000*2" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://pool1.entrustus.org:8085/api/stats"
      }
     ]
    },
    {
     "alias": "Building-138",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "poolStats",
     "select": [
      [
       { "params": [ "pools_pirate-chain_hashrate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000/1000/1000/1000*2" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://pool1.entrustus.org:8087/api/stats"
      }
     ]
    },
    {
     "alias": "Home",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "poolStats",
     "select": [
      [
       { "params": [ "pools_pirate-chain_hashrate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000/1000/1000/1000*2" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://192.168.2.231:8085/api/stats"
      }
     ]
    },
    {
     "alias": "local-138",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "poolStats",
     "select": [
      [
       { "params": [ "pools_pirate-chain_hashrate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000/1000/1000/1000*2" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://192.168.2.138:8087/api/stats"
      }
     ]
    },
    {
     "alias": "local-3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "poolStats",
     "select": [
      [
       { "params": [ "pools_pirate-chain_hashrate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000/1000/1000/1000*2" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://192.168.2.184:8085/api/stats"
      }
     ]
    }
   ]
  },
  {
   "title": "Blockchain Stats",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "MHs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Hashrate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "network_hashrate",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "pirate_wallet",
       "operator": "=",
       "value": "http://192.168.2.184:9003/metrics"
      }
     ]
    },
    {
     "alias": "Difficulty",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "difficulty",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " / 1000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "pirate_wallet",
       "operator": "=",
       "value": "http://192.168.2.184:9003/metrics"
      }
     ]
    }
   ]
  },
  {
   "title": "Block Value",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "crypto_currency",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "pair", "operator": "=", "value": "arrrusdt" }
     ]
    },
    { "expression": "$A*8", "type": "math" },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "crypto_currency",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "pair", "operator": "=", "value": "arrrusdt" }
     ]
    }
   ]
  },
  {
   "title": "Prices",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "ARRR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "crypto_currency",
     "query": "SELECT last(\"gauge\") FROM \"exchange_rate\" WHERE (\"exchange\" = 'coinex' AND \"currency\" = 'ARRR') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "kucoin" },
      { "condition": "AND", "key": "pair", "operator": "=", "value": "arrrusdt" }
     ]
    },
    {
     "alias": "BTC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "crypto_currency",
     "query": "SELECT last(\"gauge\") FROM \"exchange_rate\" WHERE (\"exchange\" = 'coinex' AND \"currency\" = 'ARRR') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "kucoin" },
      { "condition": "AND", "key": "pair", "operator": "=", "value": "btcusdt" }
     ]
    },
    { "expression": "$A/$B", "type": "math" },
    {
     "alias": "Value",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "crypto_currency",
     "query": "SELECT last(\"gauge\") FROM \"exchange_rate\" WHERE (\"exchange\" = 'coinex' AND \"currency\" = 'ARRR') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*8*.45" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "exchange", "operator": "=", "value": "kucoin" },
      { "condition": "AND", "key": "pair", "operator": "=", "value": "arrrusdt" }
     ]
    }
   ]
  },
  {
   "title": "Pool Servers Online",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 12 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "Building",
     "crit": 400,
     "displayAliasType": "Warning / Critical",
     "displayType": "Annotation",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "OnlineStatus",
     "select": [
      [
       { "params": [ "result_type" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      {
       "key": "server",
       "operator": "=",
       "value": "http://pool1.entrustus.org:8085"
      }
     ],
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 201
    },
    {
     "aggregation": "Last",
     "alias": "138",
     "crit": 400,
     "displayAliasType": "Warning / Critical",
     "displayType": "Annotation",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "OnlineStatus",
     "select": [
      [
       { "params": [ "result_type" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      {
       "key": "server",
       "operator": "=",
       "value": "http://pool1.entrustus.org:8087"
      }
     ],
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 201
    },
    {
     "aggregation": "Last",
     "alias": "home",
     "crit": 400,
     "displayAliasType": "Warning / Critical",
     "displayType": "Annotation",
     "displayValueWithAlias": "When Alias Displayed",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "OnlineStatus",
     "select": [
      [
       { "params": [ "result_type" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "http://192.168.2.231:8085" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 201
    },
    {
     "aggregation": "Last",
     "alias": "local-138",
     "crit": 400,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "OnlineStatus",
     "select": [
      [
       { "params": [ "result_type" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "http://192.168.2.138:8087" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 201
    },
    {
     "aggregation": "Last",
     "alias": "local-3",
     "crit": 400,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "OnlineStatus",
     "select": [
      [
       { "params": [ "result_type" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "http://192.168.2.175:8085" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 201
    },
    {
     "aggregation": "Last",
     "alias": "local-3",
     "crit": 400,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "OnlineStatus",
     "select": [
      [
       { "params": [ "result_type" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "http://192.168.2.184:8085" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold",
     "warn": 201
    }
   ]
  },
  {
   "title": "Hackers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "231",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "iptables_rules_total",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "iptables",
       "operator": "=",
       "value": "http://192.168.2.231:9455/metrics"
      }
     ]
    },
    {
     "alias": "local-3",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "iptables_rules_total",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "iptables",
       "operator": "=",
       "value": "http://192.168.2.175:9455/metrics"
      }
     ]
    },
    {
     "alias": "building-3",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "iptables_rules_total",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "iptables",
       "operator": "=",
       "value": "http://pool1.entrustus.org:9455/metrics"
      }
     ]
    },
    {
     "alias": "local-3",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "iptables_rules_total",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "iptables",
       "operator": "=",
       "value": "http://192.168.2.138:9455/metrics"
      }
     ]
    }
   ]
  },
  {
   "title": "Hashrate, Difficulty & Blocks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Net Hashrate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "limit": "0",
     "measurement": "network_hashrate",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "slimit": "0",
     "tags": [
      {
       "key": "pirate_wallet",
       "operator": "=",
       "value": "http://192.168.2.184:9003/metrics"
      }
     ]
    },
    {
     "alias": "Ksols Building",
     "groupBy": [
      { "params": [ "3m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "limit": "0",
     "measurement": "poolStats",
     "select": [
      [
       { "params": [ "pools_pirate-chain_hashrate" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " / 1000000000000*2" ], "type": "math" }
      ]
     ],
     "slimit": "0",
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://192.168.2.184:8085/api/stats"
      }
     ]
    },
    {
     "alias": "Ksols Home",
     "groupBy": [
      { "params": [ "3m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "limit": "0",
     "measurement": "poolStats",
     "select": [
      [
       { "params": [ "pools_pirate-chain_hashrate" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " / 1000000000000*2" ], "type": "math" }
      ]
     ],
     "slimit": "0",
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://192.168.2.231:8085/api/stats"
      }
     ]
    },
    {
     "alias": "Ksols local-138",
     "groupBy": [
      { "params": [ "3m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "limit": "0",
     "measurement": "poolStats",
     "select": [
      [
       { "params": [ "pools_pirate-chain_hashrate" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " / 1000000000000*2" ], "type": "math" }
      ]
     ],
     "slimit": "0",
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://192.168.2.138:8087/api/stats"
      }
     ]
    },
    {
     "alias": "Pending-local-3",
     "groupBy": [
      { "params": [ "3m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "limit": "0",
     "measurement": "poolStats",
     "select": [
      [
       {
        "params": [
         "pools_pirate-chain_blocks_pending"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "slimit": "0",
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://192.168.2.184:8085/api/stats"
      }
     ]
    },
    {
     "alias": "Pending-Home-231",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "limit": "0",
     "measurement": "poolStats",
     "select": [
      [
       {
        "params": [
         "pools_pirate-chain_blocks_pending"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "slimit": "0",
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://192.168.2.231:8085/api/stats"
      }
     ]
    },
    {
     "alias": "Orphaned-Home-231",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "limit": "0",
     "measurement": "poolStats",
     "select": [
      [
       {
        "params": [
         "pools_pirate-chain_blocks_orphaned"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "slimit": "0",
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://192.168.2.231:8085/api/stats"
      }
     ]
    },
    {
     "alias": "rejected-Home-231",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "limit": "0",
     "measurement": "poolStats",
     "select": [
      [
       {
        "params": [
         "pools_pirate-chain_blocks_blocksRejected"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "slimit": "0",
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "http://192.168.2.231:8085/api/stats"
      }
     ]
    }
   ]
  }
 ]
}